spring.datasource.driver-class-name=org.apache.derby.jdbc.ClientDriver
spring.datasource.username=sa
spring.datasource.password=cloud3x9
spring.datasource.url=jdbc:derby://localhost:1527/books
spring.datasource.initialize=false
spring.jpa.hibernate.ddl-auto=none